"""Update trophy cols

Revision ID: 000160f6a8da
Revises: 60697fbef586
Create Date: 2026-07-17 15:54:47.054349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '000160f6a8da'
down_revision: Union[str, None] = '60697fbef586'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trophies', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('trophies', sa.Column('icon', sa.String(length=50), nullable=True))
    op.drop_column('trophies', 'icon_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trophies', sa.Column('icon_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('trophies', 'icon')
    op.drop_column('trophies', 'description')
    # ### end Alembic commands ###
