"""Add join_requests tracking

Revision ID: 0188dd62b116
Revises: 64f52008a9ff
Create Date: 2026-07-17 15:57:30.456137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0188dd62b116'
down_revision: Union[str, None] = '64f52008a9ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('join_requests', sa.Column('form_responses', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('join_requests', sa.Column('attendance_confirmed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('join_requests', 'attendance_confirmed')
    op.drop_column('join_requests', 'form_responses')
    # ### end Alembic commands ###
