"""add social_work_days and edu_org role

Revision ID: 1e6fb1fb3bc2
Revises: a99_add_interests_and_privacy
Create Date: 2026-08-14 04:33:31.947358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e6fb1fb3bc2'
down_revision: Union[str, None] = 'a99_add_interests_and_privacy'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('social_work_days', sa.Float(), nullable=True))
    # ### end Alembic commands ###
    
    # Manually add the new enum value
    op.execute("ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'edu_org'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'social_work_days')
    # ### end Alembic commands ###
