"""Add group missing cols

Revision ID: 60697fbef586
Revises: e06a83cd43be
Create Date: 2026-07-17 15:52:27.128355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60697fbef586'
down_revision: Union[str, None] = 'e06a83cd43be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('public_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'public_description')
    # ### end Alembic commands ###
