"""Add custom forms and trophies

Revision ID: e06a83cd43be
Revises: a1b2c3d4e5f6
Create Date: 2026-07-17 15:45:29.340589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e06a83cd43be'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_forms',
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_fields',
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('field_type', sa.Enum('text', 'textarea', 'checkbox', 'number', name='field_type', create_constraint=True), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['custom_forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_fields_form_id'), 'form_fields', ['form_id'], unique=False)
    op.create_table('trophies',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('icon_url', sa.String(length=255), nullable=True),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trophies_creator_id'), 'trophies', ['creator_id'], unique=False)
    op.create_index(op.f('ix_trophies_name'), 'trophies', ['name'], unique=True)
    op.create_table('group_join_requests',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('form_responses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_active_group_request')
    )
    op.create_index(op.f('ix_group_join_requests_group_id'), 'group_join_requests', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_join_requests_user_id'), 'group_join_requests', ['user_id'], unique=False)
    op.create_table('user_trophies',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('trophy_id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trophy_id'], ['trophies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_trophies_trophy_id'), 'user_trophies', ['trophy_id'], unique=False)
    op.create_index(op.f('ix_user_trophies_user_id'), 'user_trophies', ['user_id'], unique=False)
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    op.add_column('activities', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    op.add_column('activities', sa.Column('custom_form_id', sa.UUID(), nullable=True))
    op.add_column('activities', sa.Column('trophy_id', sa.UUID(), nullable=True))
    op.drop_index('idx_activity_location', table_name='activities', postgresql_using='gist')
    op.create_index(op.f('ix_activities_trophy_id'), 'activities', ['trophy_id'], unique=False)
    op.create_foreign_key(None, 'activities', 'custom_forms', ['custom_form_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'activities', 'trophies', ['trophy_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_comments_is_deleted'), 'comments', ['is_deleted'], unique=False)
    op.drop_index('ix_content_likes_target_id', table_name='content_likes')
    op.drop_index('ix_content_likes_target_type', table_name='content_likes')
    op.create_index(op.f('ix_documents_author_id'), 'documents', ['author_id'], unique=False)
    op.create_index(op.f('ix_documents_group_id'), 'documents', ['group_id'], unique=False)
    op.create_index(op.f('ix_documents_is_deleted'), 'documents', ['is_deleted'], unique=False)
    op.add_column('groups', sa.Column('private_description', sa.Text(), nullable=True))
    op.add_column('groups', sa.Column('require_approval', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('groups', sa.Column('custom_form_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'groups', 'custom_forms', ['custom_form_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'custom_form_id')
    op.drop_column('groups', 'require_approval')
    op.drop_column('groups', 'private_description')
    op.drop_index(op.f('ix_documents_is_deleted'), table_name='documents')
    op.drop_index(op.f('ix_documents_group_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_author_id'), table_name='documents')
    op.create_index('ix_content_likes_target_type', 'content_likes', ['target_type'], unique=False)
    op.create_index('ix_content_likes_target_id', 'content_likes', ['target_id'], unique=False)
    op.drop_index(op.f('ix_comments_is_deleted'), table_name='comments')
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.drop_index(op.f('ix_activities_trophy_id'), table_name='activities')
    op.create_index('idx_activity_location', 'activities', ['location'], unique=False, postgresql_using='gist')
    op.drop_column('activities', 'trophy_id')
    op.drop_column('activities', 'custom_form_id')
    op.drop_column('activities', 'embedding')
    op.drop_index(op.f('ix_user_trophies_user_id'), table_name='user_trophies')
    op.drop_index(op.f('ix_user_trophies_trophy_id'), table_name='user_trophies')
    op.drop_table('user_trophies')
    op.drop_index(op.f('ix_group_join_requests_user_id'), table_name='group_join_requests')
    op.drop_index(op.f('ix_group_join_requests_group_id'), table_name='group_join_requests')
    op.drop_table('group_join_requests')
    op.drop_index(op.f('ix_trophies_name'), table_name='trophies')
    op.drop_index(op.f('ix_trophies_creator_id'), table_name='trophies')
    op.drop_table('trophies')
    op.drop_index(op.f('ix_form_fields_form_id'), table_name='form_fields')
    op.drop_table('form_fields')
    op.drop_table('custom_forms')
    # ### end Alembic commands ###
